version: 0.0
os: linux
files:
  # unzip the build artifact in ~/app
  - source: /
    destination: /home/ec2-user
permissions:
  # change permissions from root to ec2-user
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    # start the application
    - location: deploy/start-service.sh
      timeout: 300
      runas: ec2-user
