version: 0.0
os: linux
files:
  # unzip the build artifact in ~/app
  - source: /
    destination: /var/www/html/app/
    overwrite: true
hooks:
  BeforeInstall:
    - location: /var/www/html/app/deploy/stop_service.sh
      timeout: 300
      runas: root
  Install:
    - location: /var/www/html/app/deploy/start.sh
      timeout: 300
      runas: root
  AfterInstall:
    # start the application
    - location: /var/www/html/app/deploy/start_nginx.sh
      timeout: 300
      runas: root
