version: 0.0
os: linux
files:
  # unzip the build artifact in ~/app
  - source: /
    destination: /var/www/html/
    overwrite: true
hooks:
  BeforeInstall:
    - location: deploy/stop_service.sh
      timeout: 300
      runas: root
  Install:
    - location: deploy/start.sh
      timeout: 300
      runas: root
  AfterInstall:
    # start the application
    - location: deploy/start_nginx.sh
      timeout: 300
      runas: root
