version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo installing nodejs...
      - npm i -g @angular/cli
      - npm i -g typescript
      - echo "install nodejs"
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --prod
      - echo "build complete"
  post_build:
    commands:
      - mv appspec.yaml ./dist/learning-app
      - mv deploy ./dist/learning-app
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/learning-app
